// <auto-generated />
namespace AccountBalance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addmonthandyear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmonthandyear));
        
        string IMigrationMetadata.Id
        {
            get { return "202212280831307_add month and year"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
